FROM node:18-alpine

WORKDIR /app

# Установка зависимостей для разработки
COPY package*.json ./
RUN npm install

# Копируем весь код
COPY . .

# Открываем порт для разработки
EXPOSE 3000

# Запускаем в режиме разработки
CMD ["npm", "start"] 