version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    image: rental-backend-minimal:latest
    container_name: rental-backend-minimal
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
