apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: shepsigrad-dev
type: Opaque
data:
  # Значения должны быть закодированы в base64
  # Пример: echo -n "your_value" | base64
  DB_USERNAME: cG9zdGdyZXM=  # postgres
  DB_PASSWORD: cG9zdGdyZXM=  # postgres
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleV9oZXJl  # your_jwt_secret_key_here
  REFRESH_SECRET: eW91cl9yZWZyZXNoX3NlY3JldF9rZXlfaGVyZQ==  # your_refresh_secret_key_here
  STRIPE_SECRET_KEY: c2tfdGVzdF95b3VyX3N0cmlwZV9zZWNyZXRfa2V5  # sk_test_your_stripe_secret_key
  STRIPE_WEBHOOK_SECRET: d2hzZWNfeW91cl9zdHJpcGVfd2ViaG9va19zZWNyZXQ=  # whsec_your_stripe_webhook_secret
  MAIL_PASSWORD: eW91cl9lbWFpbF9wYXNzd29yZA==  # your_email_password
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: shepsigrad-dev
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=  # postgres
  DB_PASSWORD: cG9zdGdyZXM=  # postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: shepsigrad-dev
type: Opaque
data:
  S3_ACCESS_KEY: bWluaW8=  # minio
  S3_SECRET_KEY: bWluaW8xMjM=  # minio123
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
type: Opaque
data:
  admin-password: YWRtaW4xMjM=  # admin123
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-auth
  namespace: monitoring
type: Opaque
data:
  auth: YWRtaW46JGFwcjEkVUVxRHpqS1YkWUU5ZnJBUEpKUzJWTVRhWmZaWUZMLgo=  # admin:admin123 в формате htpasswd 