apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: rental-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rental-backend
  template:
    metadata:
      labels:
        app: rental-backend
    spec:
      containers:
      - name: backend
        image: shepsigrad-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: API_PREFIX
          value: "/api"
        - name: CORS_ORIGIN
          value: "*"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: jwt-secret
        - name: JWT_ACCESS_EXPIRES_IN
          value: "15m"
        - name: JWT_REFRESH_EXPIRES_IN
          value: "7d"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: database-url
        - name: STORAGE_PROVIDER
          value: "s3"
        - name: S3_BUCKET
          value: "rental-app"
        - name: S3_REGION
          value: "eu-central-1"
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: s3-access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: s3-secret-key
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5 