apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
data:
  # Значения должны быть закодированы в base64
  # Пример: echo -n "your-secret-value" | base64
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
  database-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGRiOjU0MzIvcmVudGFsX2FwcA==
  s3-access-key: bWluaW8=
  s3-secret-key: bWluaW8xMjM=
  supabase-url: aHR0cHM6Ly95b3VyLXN1cGFiYXNlLXVybC5zdXBhYmFzZS5jbw== # https://your-supabase-url.supabase.co
  supabase-anon-key: eW91ci1zdXBhYmFzZS1hbm9uLWtleQ== # your-supabase-anon-key
  redis-password: eW91cnBhc3N3b3Jk 